[workspace]
resolver = "3"
members = ["crates/nota-core", "crates/nota-desktop"]
default-members = ["crates/nota-desktop"]

[workspace.package]
edition = "2024"
rust-version = "1.95"
authors = ["Andrejs Strazds"]
license = "MIT"
repository = "https://github.com/astrazds/nota"

[workspace.lints.rust]
unsafe_code = "forbid"
